### PR TITLE
Add long call (hang) detection.

### PR DESCRIPTION
**Pull request by Y-Less**
This adds detection for misbehaving code that hasn't actually crashed by printing a backtrace when a callback call goes over a user-defined threshold of time.  I.e. it warns you when code takes too long.  You can set the limit (in us) low to detect slow code, or high to only detect hung code:

```
long_call_time 1000000
```

image

Addresses #65

### CODE REVIEW

**Comment by Y-Less** [comment]
The original proposal hooked `BREAK` opcodes to check the elapsed time.  This just does it in a separate thread.

**Comment by Zeex** [comment]
Nice, thanks for this PR, it's a useful feature.

Can you check the build errors on Travis CI & AppVeyor? both are failing at the moment:

https://travis-ci.org/github/Zeex/samp-plugin-crashdetect/jobs/665196488
https://ci.appveyor.com/project/Zeex/samp-plugin-crashdetect/builds/31621363

**Comment by Y-Less** [comment]
Ahh, it's because I used `chrono_literals`, which is C++14, and this isn't.  Not sure if C++11 is OK, otherwise I'll have to rewrite everything!

**Comment by Y-Less** [comment]
OK, the tests are crashing on Linux.  Not sure why, but I'll get a machine and check.

**Comment by Y-Less** [comment]
OK, I still can't get it to compile on whatever GCC this is.  It complains that `sleep_for` isn't a function.  Searching reveals that this requires the `--enable-libstdcxx-time=rt` flag, but that doesn't work.  Alternatively `-D_GLIBCXX_USE_NANOSLEEP` or `-DGLIBCXX_ENABLE_LIBSTDCXX_TIME`.  Neither of those work either.  It does seem to be an especially ancient version of GCC, I don't know if that is by design.

**Comment by Y-Less** [comment]
@Zeex Is it possible to see the test output?  Current it just shows this:

```
Running tests...

Test project /home/travis/build/Zeex/samp-plugin-crashdetect

    Start 1: args

1/7 Test #1: args .............................***Exception: Child aborted  0.11 sec

    Start 2: bounds

2/7 Test #2: bounds ...........................***Exception: Child aborted  0.10 sec

    Start 3: orte_backtrace

3/7 Test #3: orte_backtrace ...................***Exception: Child aborted  0.10 sec

    Start 4: orte_regs

4/7 Test #4: orte_regs ........................***Exception: Child aborted  0.10 sec

    Start 5: presence

5/7 Test #5: presence .........................***Exception: Child aborted  0.10 sec

    Start 6: ref_args

6/7 Test #6: ref_args .........................***Exception: Child aborted  0.10 sec

    Start 7: states

7/7 Test #7: states ...........................***Exception: Child aborted  0.10 sec

0% tests passed, 7 tests failed out of 7

Total Test time (real) =   0.74 sec

The following tests FAILED:

	  1 - args (Child aborted)

	  2 - bounds (Child aborted)

	  3 - orte_backtrace (Child aborted)

	  4 - orte_regs (Child aborted)

	  5 - presence (Child aborted)

	  6 - ref_args (Child aborted)

	  7 - states (Child aborted)

Errors while running CTest

Makefile:151: recipe for target 'test' failed
```

Which is a slight improvement, as at least it is now getting to the tests.  But I can't see where they fail.

**Comment by Zeex** [comment]
Have you tried running ctest in verbose mode?

`ctest -V -R test_name`

or

`VERBOSE=1 make test`

**Comment by Y-Less** [comment]
Wait, I hadn't fixed it yet.

**Comment by Zeex** [comment]
Don't worry, I fixed it in plugin-runner - it had something to do with the `-pthread` flag. It seems that shared libraries can't use pthreads if the executable doesn't use this flag.

**Pull request merged**
